const fs=require('fs'),path=require('path');
const WEAPONS=JSON.parse(fs.readFileSync(path.join(__dirname,'public','weapons.json'),'utf8'));
const express=require('express'),http=require('http'),{Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server,{pingTimeout:20000,pingInterval:10000});app.use(express.static('public'));
const rooms=new Map(), code=()=>Math.random().toString(36).slice(2,7).toUpperCase();
function roster(c){const r=rooms.get(c);return r?[...r.players.values()].map(p=>({id:p.id,player:p.num,hp:p.hp,name:p.name,host:p.id===r.host})):[]}
function sendRoster(c){io.to(c).emit('roster',roster(c))}
function resetRoom(c){const r=rooms.get(c);if(!r)return;for(const p of r.players.values()){p.hp=100;p.block=false;p.guard=100;p.guardBroken=false;p.ammo=WEAPONS.Gun.ammo};r.round++;r.started=true;io.to(c).emit('restart',{round:r.round});io.to(c).emit('started',{round:r.round});sendRoster(c)}
function leave(s){const c=s.data.room,r=rooms.get(c);if(!r)return;r.players.delete(s.id);if(!r.players.size){rooms.delete(c);return}if(r.host===s.id)r.host=r.players.keys().next().value;if(r.players.size<2)r.started=false;sendRoster(c);io.to(c).emit('playerLeft',{count:r.players.size})}
io.on('connection',s=>{
 s.on('create',(data,cb)=>{let c;do c=code();while(rooms.has(c));rooms.set(c,{players:new Map(),round:1,started:false,host:s.id});const r=rooms.get(c);const name=((data&&data.name)||'Player 1').trim().slice(0,16)||'Player 1';r.players.set(s.id,{id:s.id,num:1,name,hp:100,lastHit:0,block:false,guard:100,guardBroken:false,ammo:WEAPONS.Gun.ammo});s.join(c);s.data.room=c;s.data.player=1;cb({ok:true,code:c,player:1});sendRoster(c)});
 s.on('join',(data,cb)=>{const c=((data&&data.code)||'').trim().toUpperCase(),r=rooms.get(c);if(!r||r.players.size>=4)return cb({ok:false,reason:!r?'notfound':'full'});const used=new Set([...r.players.values()].map(p=>p.num));let n=1;while(used.has(n))n++;const name=((data&&data.name)||('Player '+n)).trim().slice(0,16)||('Player '+n);r.players.set(s.id,{id:s.id,num:n,name,hp:100,lastHit:0,block:false,guard:100,guardBroken:false,ammo:WEAPONS.Gun.ammo});s.join(c);s.data.room=c;s.data.player=n;cb({ok:true,code:c,player:n});sendRoster(c);io.to(c).emit('ready',{count:r.players.size})});
 s.on('start',()=>{const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.players.size<2||r.started)return;r.started=true;for(const p of r.players.values()){p.hp=100;p.block=false;p.guard=100;p.guardBroken=false;p.ammo=WEAPONS.Gun.ammo};io.to(s.data.room).emit('started',{round:r.round});sendRoster(s.data.room)});
 s.on('state',d=>{const r=rooms.get(s.data.room),me=r&&r.players.get(s.id);if(!r||!r.started||!me||!d||typeof d.s!=='object')return;me.block=!!d.s.block;me.guard=Math.max(0,Math.min(100,Number(d.s.guard)||0));me.guardBroken=!!d.s.guardBroken;s.to(s.data.room).emit('state',{s:d.s,player:me.num})});
 s.on('hit',d=>{const r=rooms.get(s.data.room),a=r&&r.players.get(s.id);if(!r||!r.started||!a||a.hp<=0)return;const now=Date.now();const target=[...r.players.values()].find(p=>p.num===Number(d.target));if(!target||target.hp<=0||target.id===s.id)return;const weapon=WEAPONS[d.weapon] ? d.weapon : 'Sword', cfg=WEAPONS[weapon], st={damage:cfg.damage,push:cfg.knockback,cool:cfg.cooldownMs};if(now-a.lastHit<st.cool)return;a.lastHit=now;const blocked=!!target.block&&!target.guardBroken&&target.guard>0;if(blocked){target.guard=Math.max(0,target.guard-st.damage*(cfg.guardDamageMultiplier||3.2));if(target.guard<=0){target.block=false;target.guardBroken=true;io.to(s.data.room).emit('guardBreak',{target:target.num})}}const dmg=blocked?Math.ceil(st.damage*.25):st.damage,push=(Number(d.dir)<0?-1:1)*(blocked?3:st.push);target.hp=Math.max(0,target.hp-dmg);io.to(s.data.room).emit('damage',{target:target.num,hp:target.hp,damage:dmg,push,attacker:a.num});sendRoster(s.data.room)});

 s.on('projectile',d=>{const r=rooms.get(s.data.room),a=r&&r.players.get(s.id);if(!r||!r.started||!a||a.hp<=0||!d)return;const now=Date.now(),type=d.type==='bullet'?'bullet':d.type==='dagger'?'dagger':null;if(!type)return;const cfg=type==='bullet'?WEAPONS.Gun:WEAPONS.Dagger,cool=cfg.cooldownMs;if(now-a.lastHit<cool)return;if(type==='bullet'){if(a.ammo<=0)return;a.ammo--;io.to(s.data.room).emit('ammo',{player:a.num,ammo:a.ammo});}a.lastHit=now;io.to(s.data.room).emit('projectile',{owner:a.num,type,x:Number(d.x)||0,y:Number(d.y)||0,dir:Number(d.dir)<0?-1:1});});
 s.on('projectileHit',d=>{const r=rooms.get(s.data.room),a=r&&r.players.get(s.id);if(!r||!r.started||!a||!d)return;const target=[...r.players.values()].find(p=>p.num===Number(d.target));if(!target||target.hp<=0||target.id===s.id)return;const type=d.type==='bullet'?'bullet':'dagger',cfg=type==='bullet'?WEAPONS.Gun:WEAPONS.Dagger,base=cfg.damage,push0=cfg.knockback;const blocked=!!target.block&&!target.guardBroken&&target.guard>0;if(blocked){target.guard=Math.max(0,target.guard-base*(cfg.guardDamageMultiplier||3));if(target.guard<=0){target.block=false;target.guardBroken=true;io.to(s.data.room).emit('guardBreak',{target:target.num})}}const dmg=blocked?Math.ceil(base*.25):base,push=(Number(d.dir)<0?-1:1)*(blocked?2:push0);target.hp=Math.max(0,target.hp-dmg);io.to(s.data.room).emit('damage',{target:target.num,hp:target.hp,damage:dmg,push,attacker:a.num});sendRoster(s.data.room);});
 s.on('reload',()=>{const r=rooms.get(s.data.room),a=r&&r.players.get(s.id);if(!r||!a)return;a.ammo=WEAPONS.Gun.ammo;io.to(s.data.room).emit('ammo',{player:a.num,ammo:a.ammo});});
 s.on('weapon',d=>{if(s.data.room&&Object.prototype.hasOwnProperty.call(WEAPONS,d&&d.weapon))s.to(s.data.room).emit('weapon',{player:s.data.player,weapon:d.weapon})});
 s.on('restart',()=>{const r=rooms.get(s.data.room);if(r&&r.players.size>=2)resetRoom(s.data.room)});s.on('disconnect',()=>leave(s));
});
server.listen(process.env.PORT||3000,()=>console.log('Stickman Online Party Brawl running'));
